name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      
      - name: Fetch Vercel Project Settings
        run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      
      - name: Build
        run: vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      
      - name: Deploy
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
